### ISSUE TITLE
Docker compose example

### ISSUE THREAD

**Issue by jonaaix** [shopware/varnish-shopware#11]
Hi, I just wanted to share a compose example, since the double quoted host definition took me some time to figure out.

```php
varnish:
    container_name: sw_varnish
    image: ghcr.io/shopware/varnish:latest
    restart: unless-stopped
    environment:
        SHOPWARE_BACKEND_HOST: php
        SHOPWARE_BACKEND_PORT: 8000
        SHOPWARE_ALLOWED_PURGER_IP: "\"php\""
    ports:
        - 8000:80
    depends_on:
        - php
    networks:
        - app
```

Also that it's mandatory to disable cache tagging, otherwise Varnish wont work with xkey due to oversized xkey header.
```yaml
shopware:
    cache:
        tagging:
            each_config: false
            each_snippet: false
            each_theme_config: false

    http_cache:
        reverse_proxy:
            enabled: true
            use_varnish_xkey: true
            hosts:
                - 'varnish'
```
